//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Order_Goods = new HashSet<Order_Goods>();
        }
    
        public int id { get; set; }
        public string Article { get; set; }
        public string ItemName { get; set; }
        public int idMeasureUnit { get; set; }
        public double Price { get; set; }
        public int idManufacturer { get; set; }
        public int idSupplier { get; set; }
        public int idCategory { get; set; }
        public double Sale { get; set; }
        public int ItemCount { get; set; }
        public string ItemPic { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Goods> Order_Goods { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
