//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public int id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronym { get; set; }
        public int idUserData { get; set; }
        public int idUserRole { get; set; }
    
        public virtual UserData UserData { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
