//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public int id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronym { get; set; }
        public int idUserData { get; set; }
        public int idUserRole { get; set; }
    
        public virtual UserData UserData { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
